export class NursingVitalsListObj
    {
        nnVitalparameterid : number;
		coretemp : string;
		centraltemp : string;
		peripheraltemp : string;
		creationtime : Date;
		cvp : string;
		diastBp : string;
		etco2 : string;
		hrRate : string;
		lax : string;
		meanBp : string;
		modificationtime : Date;
		nnVitalparameterTime : string;
		rax : string;
		rrRate : string;
		spo2 : string;
		skintemp : string;
		systBp : string;
		uhid : string;
		vpPosition : string;
		abdGrith : string;
		rbs : string;
		loggeduser : string;
		ivp : string;
		hypoglycemia : string;
		hyperglycemia : string;
		symptomaticStatus : string;
		symptomaticValue : string;
		cft : string;
		userDate : string;
		tempDifference : string;
		systiBp : string;
		diastiBp : string;
		meaniBp : string;
		entryDate : Date;
    }