    export class QIData {
        noOfBabies: number;
        noOfBabiesIp: number;
        noOfBabiesOp: number;
        noOfMortality: number;
        noOfMortalityIp: number;
        noOfMortalityOp: number;
        noOfNurses: number;
        noOfDoctors: number;
        breastFeedingRate: number;
        earlyOnsetSepsisRate: number;
        clabsiRate: number;
        centralLineUtilization: number;
        ventilatorUtilization: number;
        noOfSurgicalCases: number;
        antibioticUtilization: number;
        meanGestationWeek: number;
        meanGestationDay: number;
        meanWeight: number;
        avgLengthOfStay: number;
        readmissionRate: number;
        bedOccupancy: number;
        mortality_nec: number;
        mortality_bpd: number;
        mortality_retinopathy: number;
        mortality_vlbw: number;
        mortality_sepsis: number;
        mortality_ivh: number;
    }
