export class EmptyObj{
        nnVitalparameterid: any;
        coretemp: any;
        centraltemp: any;
        peripheraltemp: any;
        creationtime: any;
        cvp: any;
        cvpUnit: string;
        diastBp: any;
        etco2: any;
        hrRate: any;
        lax: any;
        meanBp: any;
        modificationtime: any;
        nnVitalparameterTime: string;
        rax: any;
        rrRate: any;
        spo2: any;
        skintemp: any;
        systBp: any;
        uhid: string;
        vpPosition: string;
        abdGrith: any;
        rbs: any;
        loggeduser: string;
        ivp: any;
        hypoglycemia: any;
        hyperglycemia: any;
        symptomaticStatus: boolean;
        symptomaticValue: any;
        cft: any;
        userDate: any;
        tempDifference: any;
        systiBp: any;
        diastiBp: any;
        meaniBp: any;
        entryDate: any;
        rightPupilReaction : any;
        rightPupilSize : any;
        leftPupilSize : any;
        leftPupilReaction : any;
        isPupilEqual : boolean;
}
