export class NursingIntakeEmptyObj{
  nursing_intakeid: any;
  creationtime: any;
  modificationtime: any;
  uhid: string;
  loggeduser: string;
  babyfeedid: string;
  nursingEntryTime: string;
  primaryFeedType: string;
  primaryFeedValue: any;
  formulaType: string;
  formulaValue: any;
  lipid_total_volume: any;
  lipid_delivered: any;
  lipid_remaining: any;
  tpn_total_volume: any;
  tpn_delivered: any;
  tpn_remaining: any;
  abdomenGirth: string;
  gastricAspirate: string;
  urine: string;
  cummulativeUrine ?: any;
  stool: string;
  vomit: string;
  drain: string;
  others: string;
  route: string;
  actualFeed: any;
  cummulativeEn ?: any;
  selectedPrimaryFeedType: string;
  entry_timestamp: any;

  aspirateColor : any;
  aspirateColorOther : any;
  urinePassed : any;
  stoolPassed : any;
  vomitPassed : any;
  vomitColor : any;
  vomitColorOther : any;
  outputComment : any;
  enteralComment: any;
  parenteralComment: any;
  calciumVolume: any;
  calciumComment : any;
  ironVolume : any;
  ironComment : any;
  mvVolume : any;
  mvComment : any;
  otherAdditive : any;
  otherAdditiveVolume : any;
  otherAdditiveComment : any;
  bolus_executed : boolean;
  vitamindVolume : any;
  vitamindComment : string;
  additionalPNTotalFeed : any;
  additionalPNRemainingFeed : any;
  additionalPNDeliveredFeed : any;
  aminoTotalFeed : any;
  aminoDeliveredFeed : any;
  aminoRemainingFeed : any;
  mctVolume : any;
  mctComment : string;
  siteCannula : string;
  appearance : string;
  appearanceOther : string;
}
