import { StopTime } from './stopTime';
export class BabyPrescription {
    babyPresid?: any;
    refBabyPresid : any;
    medid?: any;
    comments?: any;
    creationtime?: any;
    dose?: any;
    enddate?: any;
    frequency?: any;
    medicationtype?: any;
    medicinename?: any;
    modificationtime?: any;
    route?: any;
    startdate?: any;
    medicineOrderDate : any;
    starttime?: any;
    startTimeObject?: StopTime;
    uhid?: any;
    loggeduser?: any;
    isactive?: any;
    calculateddose?: any;
    dilusion?: any;
    frequencyInt?: any;
    medicationTypeStr?: any;
    medicationFreqStr?: any;
    eventid?: any;
    eventname?: any;
    isInEditMode: boolean;
    stopTime: StopTime;
    bolus: boolean;
    freq_type?: any;
    dilution_type?: any;
    dilution_volume?: any;
    rate?: any;
    medType ?: any;
    po_type : string;
    dose_unit : string;
    dose_unit_time : string;
    drug_strength : any;
    med_quantity : any;
    inf_volume : any;
    inf_mode : string;
    inf_time : any;
    overfill_volume : any;
    overfill_factor : any;
    actual_inf_volume : any;
    actual_med_volume : any;
    actual_dil_volume : any;
    actual_dose_volume : any;
    patient_receive : any;
    instruction : any;
    cal_dose_volume : any;
    stopMessage : any;
    topical_frequency : any;
    topical_drops : any;
    sachets : string;
    volume : number;
    volumeMeq : number;
    feedPerMl : number;
    quantity : string;
    medicineDay : number;
    isEdit : boolean;
    isContinueMedication : boolean;
    indication : string;
    isWithMilk : boolean;
}
