export class RespSupportObj {
       respsupportid?: any;
       creationtime?: any;
       modificationtime?: any;
       eventid?: any;
       eventname?: any;
       uhid?: string;
       rsVentType?: string;
       rsFlowRate?: string;
       rsFio2?: string;
       rsMap?: string;
       rsMechVentType?: string;
       rsPeep?: string;
       rsPip?: string;
       rsIt?: string;
       rsEt?: string;
       rsTv?: string;
       rsMv?: string;
       rsAmplitude?: string;
       rsFrequency?: string;
       rsRate?: string;
       rsIsEndotracheal?: string;
       rsTubeSize?: string;
       rsFixation?: string;
       rsSpo2?: string;
       rspCO2?: string;
       rsBackuprate?: string;
       isactive?: boolean;
       dco2 : string;
       iTime : string;
   }
