export class BabytpnfeedDetail {

        babytpnfeedid : any;
        actualConc : any;
        babyfeedid : any;
        calAminoacid : any;
        calCarbohydrate : any;
        calGdr : any;
        calLipid : any;
        creationtime : any;
        dextroseConc : any;
        modificationtime : any;
        pnAminoacid : any;
        pnCarbohydrate: string;
        pnGdr : any;
        pnLipid: string;
        remainingfluid : any;
        remainingfluidMlkg : any;
        targetCalorie : any;
        targetCarbohydrate : any;
        targetFat : any;
        targetProtein : any;
        totAminoacid : any;
        totCalcium : any;
        totCarbohydrate : any;
        totGdr : any;
        totLipid : any;
        totOthers : any;
        totPhosphorous : any;
        totPotassium : any;
        totSodium : any;
        totVitamin : any;
        totalCalorie : any;
        totalCarbohydrate : any;
        totalFat : any;
        totalProtein : any;
        uhid : any;
        volAminoacid : any;
        volCalcium : any;
        volCarbohydrate : any;
        volGdr : any;
        volLipid : any;
        volOthers : any;
        volPhosphorous : any;
        volPotassium : any;
        volSodium : any;
        totPnFluid : any;
        volVitamin : any;
        isTpnBabyFeedGiven : any;

}