
export class BabyfeedDetail {
	pnLipid : any;
	pnAminoacid : any;
	babyfeedid : any;
	feedText : any;
	creationtime : any;
	entryDateTime : any;
	dilution : any;
	ebm : any;
	ebmperdayml : any;
	feedduration : any;
  calsyrupDuration : any;
	ironDuration : any;
	vitaminaDuration : any;
	otherDuration : any;
	feedmethod : any;
	feedmethodList : any;
	libBreastFeed : any;
	libBreastFeedList : any;
	feedtype : any;
	feedTypeList : any;
	feedTypeSecondary : any;
	feedTypeSecondaryList : any;
	feedtypeOther : any;
	feedvolume : any;
	girvalue : any;
	formulamilk : any;
	formulamilkperdayml : any;
	hmf : any;
	hmfEbm : any;
	hmfEbmPerdayml : any;
	hmfperdayml : any;
	ivfluidmlPerhr : any;
	ivfluidrate : any;
	ivfluidtype : any;
	lbfm : any;
	lbfmperdayml : any;
	modificationtime : any;
	isNormalTpn : any;
	productmilk : any;
	isAdLibGiven : any;
	productmilkperdayml : any;
	tfi : any;
	tfm : any;
	tfmperdayml : any;
	totalIntake : any;
	totalIvfluids : any;
	totalfeedMlDay : any;
	totalivfluidMlkgday : any;
	currentDextroseConcentration : any;
	dextroseConcHigh: any;
	dextroseConcHighvolume : any;
	dextroseConcLow: any;
	dextroseConcLowvolume : any;
	isBolusGiven: boolean;
	bolusType : any;
	bolusMethod : any;
	bolusMethodList : any;
	bolusVolume : any;
	bolusFrequency : any;
	bolusTotalFeed : any;
	pastBolusObject: any[];
	pastBolusTotalFeed: any;
	aminoacidConc : any;
	aminoacidPnvolume: any;
	aminoacidTotal : any;
	enProteinEnergyRatio : any;
	enCarbohydratesLipidsRatio : any;
	totalProteinEnergyRatio : any;
	totalCarbohydratesLipidsRatio : any;
	pnProteinEnergyRatio : any;
	pnCarbohydratesLipidsRatio : any;
	calciumTotal : any;
	calciumVolume : any;
	calsyrupTotal : any;
	calsyrupVolume : any;
	enteral : any;
	hco3Total : any;
	hco3Volume : any;
	ironTotal : any;
	ironVolume : any;
	isenternalgiven : any;
	isparentalgiven : any;
	lipidConc : any;
	lipidPnvolume: any;
	lipidTotal : any;
	magnesiumTotal : any;
	magnesiumVolume : any;
	mviTotal : any;
	mviVolume : any;
	parenteral : any;
	phosphorousTotal : any;
	phosphorousVolume : any;
	potassiumTotal : any;
	potassiumVolume : any;
	sodiumTotal : any;
	sodiumVolume : any;
	vitaminaTotal : any;
	vitaminaVolume : any;
	vitamindTotal : any;
	vitamindVolume : any;
	workingWeight: any;
	additiveenteral : any;
	isAdditiveInENCalculation : any;
	additiveparenteral : any;
	dextroseVolumemlperday : any;
	totalenteralvolume : any;
	totalparenteralvolume : any;
	totalenteraAdditivelvolume: any;
	totalparenteralAdditivevolume : any;
	dextroseNetConcentration : any;
	osmolarity : any;
	isReadymadeSolutionGiven: boolean;
	readymadeFluidRate : any;
	readymadeFluidType : any;
	remainingfluid : any;
	remainingfluidMlkg : any;
	dextroseConc : any;
	readymadeFluidVolume : any;
	readymadeTotalFluidVolume : any;
	feedMethodOther : any;
	libBreastFeedOther : any;
	totalfluidMlDay : any;
	uhid : any;
	totalMedvolume : any;
	totalBloodProductVolume : number;
	totalHeplockVolume : number;
	loggeduser : any;
	isFeedGiven: boolean;
	isIVMedcineGiven : any;
	isIVFluidGiven : any;
	bolusvolume ?: any;
	feedtypeSecondary ?: any;
	enProteinIngmsEnergyRatio ?: any;
	pnProteinIngmsEnergyRatio ?: any;
	totalProteinIngmsEnergyRatio ?: any;
  calsyrupFeed : any;
	ironFeed: any;
	vitaminaFeed: any;
	otherVolume: any;
  otherTotal: any;
  otherFeed: any;
	otherAdditive: any;
  calciumConcentrationType : any;
	feedmethod_type : boolean;
	bolus_rate : number;
	bolus_infusiontime : number;
  isInfusion : boolean;
  vitaminDDuration : any;
  vitaminDFeed : any;
  ismakeDailyPN : string;
  isParenteralDextrose : boolean;
	duration : number;
	bloodProductMessage : string;
  calBrand : string;
  ironBrand : string;
  multiVitaminBrand : string;
  vitaminDBrand : string;
  otherBrand : string;
  isStrengthOther : boolean;
  unitOther : string;
	otherStrength : number;
	sodiumMeg : any;
	isRevise : boolean;
	additionalVolume : number;
	additionalKCL : number;
	additionalPNType : string;
	additionalTotalVolume : number;
	additionalDuration : number;
	additionalRate : number;
	stopPN : boolean;
	stopAdditionalPN : boolean;
	mctVolume : any;
	mctBrand : string;
	mctTotal : any;
	mctDuration : any;
	mctFeed : any;
	isAminoRate : boolean;
	isGirCalculate : boolean;
	readymadeDextroseConcentration : any;
	readymadeDextroseConcLow : any;
	readymadeDextroseConcLowType : any;
	readymadeDextroseConcLowvolume : any;
	readymadeDextroseConcHigh : any;
	readymadeDextroseConcHighType : any;
	readymadeDextroseConcHighvolume : any;
	fluidTypeList : any;
	readymadeFluidTypeList : any;
}
